name: Validate Number Input

on:
  workflow_dispatch:
    inputs:
      number_input:
        description: 'any number'
        required: true
        type: string
        default: '1'

jobs:
  validate_number:
    runs-on: ubuntu-latest
    steps:
      - name: Check if the input is a number
        run: |
          if ! [[ "${{ github.event.inputs.number_input }}" =~ ^[0-9]+$ ]]; then
            echo "Error: The input is not a valid number."
            exit 1
          else
            echo "The input is a valid number: ${{ github.event.inputs.number_input }}"
          fi
