name: Get User Email

on:
  push:
    branches:
      - main

jobs:
  get_user_email:
    runs-on: ubuntu-latest
    name: A job to get a user's email
    steps:
      - name: Get user email
        id: get-email
        run: |
          # Fetch user email using GitHub API
          response=$(curl -s -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
            https://api.github.com/users/${{ github.actor }})
          
          # Extract email from the response
          email=$(echo "$response" | jq -r '.email')
          
          if [ "$email" = "null" ] || [ -z "$email" ]; then
            echo "No email found for user ${{ github.actor }}."
            echo "EMAIL_NOT_FOUND=true" >> $GITHUB_ENV
          else
            echo "The email is $email."
            echo "EMAIL=$email" >> $GITHUB_ENV
          fi

      - name: Print the found email
        if: env.EMAIL_NOT_FOUND != 'true'
        run: echo "The email is ${{ env.EMAIL }}"

      - name: Notify email not found
        if: env.EMAIL_NOT_FOUND == 'true'
        run: echo "Email not found for user ${{ github.actor }}."
