name: Print Email ID

on: [push, pull_request]

jobs:
  print-email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get GitHub user email
        id: get_user_email
        run: |
          # Fetch the actor's email using GitHub API
          response=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                          -H "Accept: application/vnd.github.v3+json" \
                          https://api.github.com/users/${{ github.actor }})
          email=$(echo "$response" | jq -r '.email')
          echo "User email: $email"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
